FROM apache/airflow:2.9.1

# Pre-instalar dependencias del proyecto para evitar pip install en runtime
RUN pip install --no-cache-dir \
    "xgboost>=2.0.0" \
    "optuna>=3.6.0" \
    "mlflow==2.13.0" \
    "scikit-learn>=1.4.0" \
    "boto3>=1.34.0" \
    "s3fs>=2024.1.0"
